; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:uno]
platform = atmelavr
board = uno
framework = arduino
build_src_filter = +<arduino_base/>
build_flags = -Iinclude/arduino_base
lib_deps = 
	seeed-studio/Grove - LCD RGB Backlight @ ^1.0.0
	br3ttb/PID@^1.2.1

[env:esp32dev]
platform = espressif32
board = esp32dev
framework = espidf
board_build.partitions = partitions.csv

build_flags = 
    -Iinclude/esp32_rotor 
    -D ESP32_ENV
    -std=gnu++17
    -fexceptions
build_unflags = -std=gnu++11
monitor_speed = 115200

; Comando para upload via OTA. Descomente para usar.
; Note que é necessário ter o curl instalado na máquina.
upload_protocol = custom
upload_command = curl -v -X POST --data-binary @"$SOURCE" http://relogio.local/update
